name: 'Deploy Wiki'

on:
  push:
    branches: [main]
    paths: [/wiki]
  workflow_dispatch:
    
jobs:
  deploy-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          path: repo
          submodules: false
          
      - name: Copy wiki
        run: |
          cp -r repo/wiki wiki
          
      - name: Push wiki
        run: |
          cd wiki
          git config --global init.defaultBranch main
          git config --global user.name 'Wiki Pusher'
          git config --global user.email 'actions@github.com'
          
          git init
          git remote add origin https://github.com/dorianim/wiki-deploy.wiki.git
          git add --all -f
          git commit -am "Update wiki"
          git push -f
